# Generated by Django 6.0 on 2025-12-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_cf_latent_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('REPORT', 'Report'), ('NOT_INTERESTED', 'Not Interested')], max_length=20),
        ),
    ]
