# Generated by Django 6.0 on 2025-12-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_userinteraction_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('VIEW', 'View'), ('LIKE', 'Like'), ('COMMENT', 'Comment'), ('NOT_INTERESTED', 'Not Interested')], max_length=20),
        ),
    ]
