# Generated by Django 6.0 on 2025-12-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_reported',
        ),
    ]
