# Generated by Django 6.0 on 2025-12-22 03:39

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0003_userinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='posts.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='preference_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
