# Generated by Django 6.0 on 2025-12-22 07:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_interested_categories_user_preference_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cf_latent_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=64, null=True),
        ),
    ]
