# Generated by Django 6.0 on 2025-12-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cf_latent_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, storage='accounts.storage.ProfileImageStorage', upload_to='profile_images/'),
        ),
    ]
