# Generated by Django 6.0 on 2025-12-25 06:54

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pass_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.ProfileImageStorage(), upload_to='profile_images/'),
        ),
    ]
